version: '3.7'

services:
  prometheus:
    image: prom/prometheus:v2.21.0
    container_name: prometheus
    user: root
    volumes:
      - /etc/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
      - '--web.listen-address=:9090'
      - '--storage.tsdb.retention.time=15d'
      - '--storage.tsdb.min-block-duration=2h'
      - '--storage.tsdb.max-block-duration=2h'
    ports:
      - "9090:9090"
    restart: unless-stopped

  thanos_sidecar:
    image: quay.io/thanos/thanos:v0.34.1
    container_name: thanos_sidecar
    user: root
    volumes:
      - prometheus_data:/prometheus
      - /etc/thanos:/etc/thanos
    command:
      - sidecar
      - '--tsdb.path=/prometheus'
      - '--prometheus.url=http://prometheus:9090'
      - '--http-address=0.0.0.0:19191'
      - '--grpc-address=0.0.0.0:19090'
      - '--objstore.config-file=/etc/thanos/bucket_config.yaml'
    depends_on:
      - prometheus
    ports:
      - "19191:19191"
      - "19090:19090"
    restart: unless-stopped

volumes:
  prometheus_data: