FROM public.ecr.aws/lambda/python:3.9
WORKDIR /app
COPY ./requirements.txt /app
COPY ./requirements.docker.txt /app
RUN python -m pip install -r requirements.docker.txt
COPY . /app
CMD ["fetch_daily_summaries.lambda_handler"]