name: "Set AWS Credentials"
description: "Sets AWS credentials based on the provided environment name."
inputs:
  DEV_AWS_ACCESS_KEY_ID:
    description: "The AWS access key ID for the development environment."
    required: true
  DEV_AWS_SECRET_ACCESS_KEY:
    description: "The AWS secret access key for the development environment."
    required: true
  ENVIRONMENT_NAME:
    description: "The name of the environment to set the AWS credentials for."
    required: true
  PROD_AWS_ACCESS_KEY_ID:
    description: "The AWS access key ID for the production environment."
    required: true
  PROD_AWS_SECRET_ACCESS_KEY:
    description: "The AWS secret access key for the production environment."
    required: true
  STAGE_AWS_ACCESS_KEY_ID:
    description: "The AWS access key ID for the staging environment."
    required: true
  STAGE_AWS_SECRET_ACCESS_KEY:
    description: "The AWS secret access key for the staging environment."
    required: true

runs:
  using: "node20"
  main: "set-aws-credentials.js"
