name: Tests

on:
  pull_request:
    paths:
      - "orchestration/**/*.py"

jobs:
  python-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies and run tests
        run: |
          find ./orchestration/ -name 'requirements.txt' | while read requirements; do
            if [[ $requirements == *"/orchestration/"* ]]; then
              dir=$(dirname "$requirements")
              echo "Installing dependencies in $dir"
              pip install -r "$requirements"
            fi
          done
          pytest orchestration/

      - name: Check test coverage
        run: |
          coverage run -m pytest orchestration/
          coverage report -m --fail-under=80
  javascript-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test
